USE TicketsApi
go

IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'Ticket'))
BEGIN
	CREATE TABLE [Ticket](
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[User] varchar(150), 
		[Status] varchar(150), 
		[CreatedAt] DATETIME DEFAULT(GETDATE()),
		[UpdatedAt] DATETIME DEFAULT(GETDATE()), 
	 CONSTRAINT [PK_Ticket] PRIMARY KEY CLUSTERED 
	([Id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
END
GO

select * from  [Ticket]